BethanysPieShop/Controllers/PieController.cs
using BethanysPieShop.Models;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult List(string category)
        {
            //ViewBag.CurrentCategory = "Cheese cakes";

            //return View(_pieRepository.AllPies);
            PieListViewModel piesListViewModel;
            if (category == null)
            {
                category = "All Pies";
                piesListViewModel = new PieListViewModel(_pieRepository.AllPies, category);
            } else
            {
                var pies = _pieRepository.AllPies.Where(p => p.Category.CategoryName == category);
                piesListViewModel = new PieListViewModel(pies, category);
            }

            return View(piesListViewModel);
        }

        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();

            return View(pie);
        }

        public IActionResult CategoryList(int categoryId, int numberToShow = 10) {

            ViewBag.NumberToShow = numberToShow;

            var filteredPies = _pieRepository.AllPies.Where(p => p.CategoryId == categoryId).Take(numberToShow).ToList();
    
            return View(filteredPies);
        }
    }
}

BethanysPieShop/Controllers/ShoppingCartController.cs
using BethanysPieShop.Models;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private IShoppingCart _shoppingCart;
        private IPieRepository _pieRepository;

        public ShoppingCartController(IShoppingCart cart, IPieRepository repo)
        {
            _shoppingCart = cart;
            _pieRepository = repo;
        }

        public IActionResult Index()
        {
            var shoppingCartViewModel = new ShoppingCartViewModel(
                _shoppingCart.GetShoppingCartItems(),
                _shoppingCart.GetShoppingCartTotal());

            return View(shoppingCartViewModel);
        }

        public IActionResult AddToShoppingCart(int pieId)
        {
            Pie? selectedPie = _pieRepository.GetPieById(pieId);

            if (selectedPie is not null)
            {
                _shoppingCart.AddToCart(selectedPie);
            }
            return RedirectToAction(nameof(Index));
        }

        public RedirectToActionResult RemoveFromShoppingCart(int pieId)
        {
            Pie? selectedPie = _pieRepository.GetPieById(pieId);

            if (selectedPie != null)
            {
                _shoppingCart.RemoveFromCart(selectedPie);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

BethanysPieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bethany's Pie Shop</title>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css'>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    <base href="/" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary"
                 aria-label="Bethany's Pie Shop navigation header">
                <div class="container-xl">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <img src="images/bethanys-pie-shop-logo_horiz-white.png" width="151" height="47" class="d-inline-block align-top mb-2 mt-1"
                             alt="Bethany's Pie Shop Logo">
                    </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
@*                              <li class="nav-item">
                                <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                            </li>
                             <li class="nav-item">
                                <a asp-controller="Pie" asp-action="List" class="nav-link">Pies</a>
                            </li> *@
                            <vc:category-menu></vc:category-menu>
                        </ul>
                        <vc:shopping-cart-summary></vc:shopping-cart-summary>
                    </div>
                </div>
            </nav>
        </header>

        @RenderBody()
    </div>
</body>
</html>

BethanysPieShop/Views/Shared/_PieCard.cshtml
@model Pie
<div class="col">
    <div class="card pie-card">
        <img src="@Model.ImageThumbnailUrl" class="card-img-top" alt="@Model.Name">
        <div class="card-body pie-button">
            <h4 class="d-grid">
                <a class="btn btn-secondary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId"> + Add to cart</a>
            </h4>

            <div class="d-flex justify-content-between mt-2">
                <h2 class="text-start">
                    <a asp-controller="Pie"
                       asp-action="Details"
                       asp-route-id="@Model.PieId"
                       class="pie-link">@Model.Name</a>
                </h2>
                <h5 class="text-nowrap">
                    @Model.Price.ToString("c")
                </h5>
            </div>
        </div>
    </div>
</div>